---
title: "HW11"
author: "Paul Widhalm"
date: "November 25, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
  library(fpp)
  data("ukcars")
  fitd<-decompose(ukcars)
  fitdseas<-seasadj(fitd)
  ucarTS1<-ts(c(ukcars[1:54],ukcars[119],ukcars[120:121]),start=c(1996,1),frequency=12)
  ucarTS2<-ts(c(ukcars[1:54],ukcars[119]+500,ukcars[120:121]),start=c(1996,1),frequency=12)
  ucarTS3<-ts(c(ukcars[1:54],ukcars[1]+500,ukcars[120:121]),start=c(1996,1),frequency=12)
  fit<-stl(ukcars,s.window = 5)
  
```


## Data Plots
## UK Cars, there was a trough in the 1980s but a steady increase since then

```{r1, echo=FALSE}
  plot(ukcars)

```


## Decomposition
## This chart affirms was is shown in the previous chart

```{r2, echo=FALSE}
  plot(fitd)

```



## Seasonally Adjusted

```{r3, echo=FALSE}
  plot(fitdseas)

```


## Time Series, no Adjustments

```{r4, echo=FALSE}
  plot(ucarTS1)

```


## Time Series, Adjusted in the middle

```{r5, echo=FALSE}
  plot(ucarTS2)

```


## Time Series, Adjusted at the end
## where the outliuer is does make a difference

```{r50, echo=FALSE}
  plot(ucarTS3)

```



## Seasonal and Trend Decomposition

```{r6, echo=FALSE}
  plot(fit)


```